### ISSUE TITLE
SDK should return render result even if adding it to the cache fails

### ISSUE THREAD

**Issue by kevinwilde** [coursehero/theia-php#2]
We are using Dynamo DB to cache the render results. We have a couple pages that exceed the allowed item size on Dynamo DB, so this line causes an exception:
https://github.com/coursehero/theia-php/blob/6684164f0e34f3eeefbcc8e151d60f1f03ae588e/src/Client.php#L101

Perhaps we shouldn't use Dynamo DB, but the general point still stands. If `cachingInterface->set` throws an exception, we should still be able to return the render result.

We can notify that the caching failed by adding a property on the `RenderResult` class similar to the `retrievedFromCache` property

**Comment by kevinwilde** [comment]
Actually, on second thought, maybe we should be handling this error in our implementation of the `CachingInterface`

**Comment by connorjclark** [comment]
> Actually, on second thought, maybe we should be handling this error in our implementation of the CachingInterface

I think that's the cleaner approach.
